spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: kyaw549235
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka